blank_issues_enabled: false
contact_links:
  - name: Community Support (Discord channel)
    url: https://discord.gg/P4VE9UY9gJ
    about: Please ask and answer support "how do I?"questions here.
  - name: Discussion Forum
    url: https://github.com/SoftFever/OrcaSlicer/discussions
    about: Please raise ideas and feature suggestions here.
