var LangTextMyPoint = {
  zh_CN: {
    orca_list_mypoints: "我的积分",
    orca_list_thirdmodel: "三方模型库",
    image_generate_3d: "AI模型生成",
    orca_list_mypoints_benefits_title: '积分权益',
    orca_list_mypoints_benefits_current: '当前积分额度',
    orca_list_mypoints_login: '登录后查看',
    Login: '登录',
    orca_list_mypoints_benefits_view_btn: '去查看',
    orca_list_mypoints_benefits_soon_tip: '敬请期待',
    orca_list_mypoints_earn_title: '获取积分',
    orca_list_mypoints_earn_get_btn: '去获取',
    orca_list_mypoints_earn_got_btn: '已获取',
    Earned: '已获得',
    points: '积分',
    orca_list_mypoints_history_title: '积分明细',
    orca_list_mypoints_history_all_btn: '所有',
    orca_list_mypoints_history_earnings_btn: '收入',
    orca_list_mypoints_history_expenses_btn: '支出',
    orca_list_mypoints_history_totalearnings: '总收入: ',
    orca_list_mypoints_history_totalexpenses: '总支出: ',
    orca_list_mypoints_history_time: '时间',
    orca_list_mypoints_history_action: '行为',
    orca_list_recent_aitopic_tips: '一键生成专属 AI模型',
  },
  en: {
    orca_list_mypoints: "My Points",
    orca_list_thirdmodel: "3D Model Hub",
    image_generate_3d: "AI model generation",
    orca_list_mypoints_benefits_title: 'Points Benefits',
    orca_list_mypoints_benefits_current: 'Current Points',
    orca_list_mypoints_login: 'Log in to view',
    Login: 'Login',
    orca_list_mypoints_benefits_view_btn: 'View Now',
    orca_list_mypoints_benefits_soon_tip: 'Coming Soon',
    orca_list_mypoints_earn_title: 'Earn Points',
    orca_list_mypoints_earn_get_btn: 'Get Now',
    orca_list_mypoints_earn_got_btn: 'Got',
    Earned: 'Earned',
    points: 'points',
    orca_list_mypoints_history_title: 'Points History',
    orca_list_mypoints_history_all_btn: 'All',
    orca_list_mypoints_history_earnings_btn: 'Earned',
    orca_list_mypoints_history_expenses_btn: 'Spent',
    orca_list_mypoints_history_totalearnings: 'Total Earned: ',
    orca_list_mypoints_history_totalexpenses: 'Total Spent: ',
    orca_list_mypoints_history_time: 'Time',
    orca_list_mypoints_history_action: 'Action',
    orca_list_recent_aitopic_tips: 'One click to generate your custom AI model',
  },
  ko_KR: {
    orca_list_mypoints: "내 포인트",
    orca_list_thirdmodel: "3D 모델 허브",
    image_generate_3d: "AI 모델 생성",
    orca_list_mypoints_benefits_title: '포인트 혜택',
    orca_list_mypoints_benefits_current: '현재 포인트',
    orca_list_mypoints_login: '로그인하여 보기',
    Login: '로그인',
    orca_list_mypoints_benefits_view_btn: '지금 보기',
    orca_list_mypoints_benefits_soon_tip: '곧 출시 예정',
    orca_list_mypoints_earn_title: '포인트 획득',
    orca_list_mypoints_earn_get_btn: '지금 받기',
    orca_list_mypoints_earn_got_btn: '이미 받았습니다',
    Earned: '획득',
    points: '포인트',
    orca_list_mypoints_history_title: '포인트 내역',
    orca_list_mypoints_history_all_btn: '전체 포인트',
    orca_list_mypoints_history_earnings_btn: '획득 포인트',
    orca_list_mypoints_history_expenses_btn: '사용 포인트',
    orca_list_mypoints_history_totalearnings: '총 획득 포인트: ',
    orca_list_mypoints_history_totalexpenses: '총 사용 포인트: ',
    orca_list_mypoints_history_time: '시간',
    orca_list_mypoints_history_action: '활동',
    orca_list_recent_aitopic_tips: '한 번의 클릭으로 맞춤형 AI 모델 생성',
  },
  de_DE: {
    orca_list_mypoints: "Meine Punkte",
    orca_list_thirdmodel: "3D-Modell-Hub",
    image_generate_3d: "KI-Modellerzeugung",
    orca_list_mypoints_benefits_title: 'Punktevorteile',
    orca_list_mypoints_benefits_current: 'Aktuelle Punkte',
    orca_list_mypoints_login: 'Anmelden, zum Anzeigen',
    Login: 'Anmelden',
    orca_list_mypoints_benefits_view_btn: 'Jetzt ansehen',
    orca_list_mypoints_benefits_soon_tip: 'Demnächst',
    orca_list_mypoints_earn_title: 'Punkte sammeln',
    orca_list_mypoints_earn_get_btn: 'Jetzt abholen',
    orca_list_mypoints_earn_got_btn: 'Verstanden',
    Earned: 'Verdiente',
    points: 'Punkte',
    orca_list_mypoints_history_title: 'Punkte Historie',
    orca_list_mypoints_history_all_btn: 'Alle',
    orca_list_mypoints_history_earnings_btn: 'Verdient',
    orca_list_mypoints_history_expenses_btn: 'Ausgegeben',
    orca_list_mypoints_history_totalearnings: 'Verdient insgesamt: ',
    orca_list_mypoints_history_totalexpenses: 'Insgesamt ausgegeben: ',
    orca_list_mypoints_history_time: 'Zeit',
    orca_list_mypoints_history_action: 'Aktion',
    orca_list_recent_aitopic_tips: 'Mit einem Klick Ihr individuelles KI-Modell generieren',
  },
  fr_FR: {
    orca_list_mypoints: "Mes points",
    orca_list_thirdmodel: "Plateforme de modèles 3D",
    image_generate_3d: "Génération de modèle IA",
    orca_list_mypoints_benefits_title: 'Avantages des points',
    orca_list_mypoints_benefits_current: 'Points actuels',
    orca_list_mypoints_login: 'Connectez-vous pour voir',
    Login: 'Connexion',
    orca_list_mypoints_benefits_view_btn: 'Voir maintenant',
    orca_list_mypoints_benefits_soon_tip: 'Bientôt disponibles',
    orca_list_mypoints_earn_title: 'Gagnez des points',
    orca_list_mypoints_earn_get_btn: 'Obtenez maintenant',
    orca_list_mypoints_earn_got_btn: 'Compris',
    Earned: 'A gagné',
    points: 'points',
    orca_list_mypoints_history_title: 'Historique des points',
    orca_list_mypoints_history_all_btn: 'Tous',
    orca_list_mypoints_history_earnings_btn: 'Gagnés',
    orca_list_mypoints_history_expenses_btn: 'Échangés',
    orca_list_mypoints_history_totalearnings: 'Total gagnés: ',
    orca_list_mypoints_history_totalexpenses: 'Total échangés: ',
    orca_list_mypoints_history_time: 'Heure',
    orca_list_mypoints_history_action: 'Action',
    orca_list_recent_aitopic_tips: 'Un clic pour générer votre modèle IA personnalisé',
  },
  lt_LT: {
    orca_list_mypoints: "I Miei Punti",
    orca_list_thirdmodel: "Hub Modelli 3D",
    image_generate_3d: "Generazione di modelli IA",
    orca_list_mypoints_benefits_title: 'Vantaggi dei Punti',
    orca_list_mypoints_benefits_current: 'Punti Attuali',
    orca_list_mypoints_login: 'Accedi per visualizzare',
    Login: 'Prisijungti',
    orca_list_mypoints_benefits_view_btn: 'Visualizza Ora',
    orca_list_mypoints_benefits_soon_tip: 'Disponibile a Breve',
    orca_list_mypoints_earn_title: 'Guadagna Punti',
    orca_list_mypoints_earn_get_btn: 'Ottieni Ora',
    orca_list_mypoints_earn_got_btn: 'Ottenuto',
    Earned: 'Ottenuto',
    points: 'Punti',
    orca_list_mypoints_history_title: 'Cronologia dei Punti',
    orca_list_mypoints_history_all_btn: 'Tutto',
    orca_list_mypoints_history_earnings_btn: 'Guadagnato',
    orca_list_mypoints_history_expenses_btn: 'Speso',
    orca_list_mypoints_history_totalearnings: 'Totale Guadagnato: ',
    orca_list_mypoints_history_totalexpenses: 'Totale Speso: ',
    orca_list_mypoints_history_time: 'Tempo',
    orca_list_mypoints_history_action: 'Azione',
    orca_list_recent_aitopic_tips: 'Un clic per generare il tuo modello AI personalizzato',
  },
  es_ES: {
    orca_list_mypoints: "Mis Puntos",
    orca_list_thirdmodel: "Centro de Modelos 3D",
    image_generate_3d: "Generación de modelos de IA",
    orca_list_mypoints_benefits_title: 'Beneficios de Puntos',
    orca_list_mypoints_benefits_current: 'Puntos Actuales',
    orca_list_mypoints_login: 'Inicia sesión para ver',
    Login: 'Ingresar',
    orca_list_mypoints_benefits_view_btn: 'Ver Ahora',
    orca_list_mypoints_benefits_soon_tip: 'Próximamente',
    orca_list_mypoints_earn_title: 'Ganar Puntos',
    orca_list_mypoints_earn_get_btn: 'Obtener Ahora',
    orca_list_mypoints_earn_got_btn: 'Entendido',
    Earned: 'Se ganaron',
    points: 'puntos',
    orca_list_mypoints_history_title: 'Historial de Puntos',
    orca_list_mypoints_history_all_btn: 'Todos',
    orca_list_mypoints_history_earnings_btn: 'Ganados',
    orca_list_mypoints_history_expenses_btn: 'Gastados',
    orca_list_mypoints_history_totalearnings: 'Total Ganado: ',
    orca_list_mypoints_history_totalexpenses: 'Total Gastado: ',
    orca_list_mypoints_history_time: 'Hora',
    orca_list_mypoints_history_action: 'Acción',
    orca_list_recent_aitopic_tips: 'Un clic para generar tu modelo IA personalizado',
  },
  ru_RU: {
    orca_list_mypoints: "Мои баллы",
    orca_list_thirdmodel: "Хаб 3D-модели",
    image_generate_3d: "Генерация модели ИИ",
    orca_list_mypoints_benefits_title: 'Преимущества баллов',
    orca_list_mypoints_benefits_current: 'Текущие баллы',
    orca_list_mypoints_login: 'Войдите в систему для просмотра',
    Login: 'Войти',
    orca_list_mypoints_benefits_view_btn: 'Смотрите прямо сейчас',
    orca_list_mypoints_benefits_soon_tip: 'Скоро будет',
    orca_list_mypoints_earn_title: 'Зарабатывайте баллы',
    orca_list_mypoints_earn_get_btn: 'Получить сейчас',
    orca_list_mypoints_earn_got_btn: 'Получил',
    Earned: 'Заработано ',
    points: 'баллов',
    orca_list_mypoints_history_title: 'История баллов',
    orca_list_mypoints_history_all_btn: 'Все',
    orca_list_mypoints_history_earnings_btn: 'Заработано',
    orca_list_mypoints_history_expenses_btn: 'Потрачено',
    orca_list_mypoints_history_totalearnings: 'Итого заработано: ',
    orca_list_mypoints_history_totalexpenses: 'Итого потрачено: ',
    orca_list_mypoints_history_time: 'Время',
    orca_list_mypoints_history_action: 'Действие',
    orca_list_recent_aitopic_tips: 'Одним нажатием создайте свою пользовательскую ИИ‑модель',
  },
  ca_ES: {
    orca_list_mypoints: "My Points",
    orca_list_thirdmodel: "3D Model Hub",
    image_generate_3d: "Generación de modelos de IA",
    orca_list_mypoints_benefits_title: 'Points Benefits',
    orca_list_mypoints_benefits_current: 'Current Points',
    orca_list_mypoints_login: 'Log in to view',
    Login: 'Login',
    orca_list_mypoints_benefits_view_btn: 'View Now',
    orca_list_mypoints_benefits_soon_tip: 'Coming Soon',
    orca_list_mypoints_earn_title: 'Earn Points',
    orca_list_mypoints_earn_get_btn: 'Get Now',
    orca_list_mypoints_earn_got_btn: 'Got',
    Earned: 'Earned',
    points: 'points',
    orca_list_mypoints_history_title: 'Points History',
    orca_list_mypoints_history_all_btn: 'All',
    orca_list_mypoints_history_earnings_btn: 'Earned',
    orca_list_mypoints_history_expenses_btn: 'Spent',
    orca_list_mypoints_history_totalearnings: 'Total Earned: ',
    orca_list_mypoints_history_totalexpenses: 'Total Spent: ',
    orca_list_mypoints_history_time: 'Time',
    orca_list_mypoints_history_action: 'Action',
    orca_list_recent_aitopic_tips: 'One click to generate your custom AI model',
  },
  cs_CZ: {
    orca_list_mypoints: "My Points",
    orca_list_thirdmodel: "3D Model Hub",
    image_generate_3d: "AI model generation",
    orca_list_mypoints_benefits_title: 'Points Benefits',
    orca_list_mypoints_benefits_current: 'Current Points',
    orca_list_mypoints_login: 'Log in to view',
    Login: 'Login',
    orca_list_mypoints_benefits_view_btn: 'View Now',
    orca_list_mypoints_benefits_soon_tip: 'Coming Soon',
    orca_list_mypoints_earn_title: 'Earn Points',
    orca_list_mypoints_earn_get_btn: 'Get Now',
    orca_list_mypoints_earn_got_btn: 'Got',
    Earned: 'Earned',
    points: 'points',
    orca_list_mypoints_history_title: 'Points History',
    orca_list_mypoints_history_all_btn: 'All',
    orca_list_mypoints_history_earnings_btn: 'Earned',
    orca_list_mypoints_history_expenses_btn: 'Spent',
    orca_list_mypoints_history_totalearnings: 'Total Earned: ',
    orca_list_mypoints_history_totalexpenses: 'Total Spent: ',
    orca_list_mypoints_history_time: 'Time',
    orca_list_mypoints_history_action: 'Action',
    orca_list_recent_aitopic_tips: 'One click to generate your custom AI model',
  },
  zh_TW: {
    orca_list_mypoints: "我的积分",
    orca_list_thirdmodel: "三方模型库",
    image_generate_3d: "AI模型生成",
    orca_list_mypoints_benefits_title: '积分权益',
    orca_list_mypoints_benefits_current: '当前积分额度',
    orca_list_mypoints_login: '登录后查看',
    Login: 'Login',
    orca_list_mypoints_benefits_view_btn: '去查看',
    orca_list_mypoints_benefits_soon_tip: '敬请期待',
    orca_list_mypoints_earn_title: '获取积分',
    orca_list_mypoints_earn_get_btn: '去获取',
    orca_list_mypoints_earn_got_btn: '已获取',
    Earned: '已获得',
    points: 'points',
    orca_list_mypoints_history_title: '积分明细',
    orca_list_mypoints_history_all_btn: '所有',
    orca_list_mypoints_history_earnings_btn: '收入',
    orca_list_mypoints_history_expenses_btn: '支出',
    orca_list_mypoints_history_totalearnings: '总收入: ',
    orca_list_mypoints_history_totalexpenses: '总支出: ',
    orca_list_mypoints_history_time: '时间',
    orca_list_mypoints_history_action: '行为',
    orca_list_recent_aitopic_tips: '一键生成专属 AI模型',
  },
  tr_TR: {
    orca_list_mypoints: "My Points",
    orca_list_thirdmodel: "3D Model Hub",
    image_generate_3d: "AI model generation",
    orca_list_mypoints_benefits_title: 'Points Benefits',
    orca_list_mypoints_benefits_current: 'Current Points',
    orca_list_mypoints_login: 'Log in to view',
    Login: 'Login',
    orca_list_mypoints_benefits_view_btn: 'View Now',
    orca_list_mypoints_benefits_soon_tip: 'Coming Soon',
    orca_list_mypoints_earn_title: 'Earn Points',
    orca_list_mypoints_earn_get_btn: 'Get Now',
    orca_list_mypoints_earn_got_btn: 'Got',
    Earned: 'Earned',
    points: 'points',
    orca_list_mypoints_history_title: 'Points History',
    orca_list_mypoints_history_all_btn: 'All',
    orca_list_mypoints_history_earnings_btn: 'Earned',
    orca_list_mypoints_history_expenses_btn: 'Spent',
    orca_list_mypoints_history_totalearnings: 'Total Earned: ',
    orca_list_mypoints_history_totalexpenses: 'Total Spent: ',
    orca_list_mypoints_history_time: 'Time',
    orca_list_mypoints_history_action: 'Action',
    orca_list_recent_aitopic_tips: 'One click to generate your custom AI model',
  },
  pl_PL: {
    orca_list_mypoints: "My Points",
    orca_list_thirdmodel: "3D Model Hub",
    image_generate_3d: "AI model generation",
    orca_list_mypoints_benefits_title: 'Points Benefits',
    orca_list_mypoints_benefits_current: 'Current Points',
    orca_list_mypoints_login: 'Log in to view',
    Login: 'Login',
    orca_list_mypoints_benefits_view_btn: 'View Now',
    orca_list_mypoints_benefits_soon_tip: 'Coming Soon',
    orca_list_mypoints_earn_title: 'Earn Points',
    orca_list_mypoints_earn_get_btn: 'Get Now',
    orca_list_mypoints_earn_got_btn: 'Got',
    Earned: 'Earned',
    points: 'points',
    orca_list_mypoints_history_title: 'Points History',
    orca_list_mypoints_history_all_btn: 'All',
    orca_list_mypoints_history_earnings_btn: 'Earned',
    orca_list_mypoints_history_expenses_btn: 'Spent',
    orca_list_mypoints_history_totalearnings: 'Total Earned: ',
    orca_list_mypoints_history_totalexpenses: 'Total Spent: ',
    orca_list_mypoints_history_time: 'Time',
    orca_list_mypoints_history_action: 'Action',
    orca_list_recent_aitopic_tips: 'One click to generate your custom AI model',
  },
  pt_BR: {
    orca_list_mypoints: "My Points",
    orca_list_thirdmodel: "3D Model Hub",
    image_generate_3d: "AI model generation",
    orca_list_mypoints_benefits_title: 'Points Benefits',
    orca_list_mypoints_benefits_current: 'Current Points',
    orca_list_mypoints_login: 'Log in to view',
    Login: 'Login',
    orca_list_mypoints_benefits_view_btn: 'View Now',
    orca_list_mypoints_benefits_soon_tip: 'Coming Soon',
    orca_list_mypoints_earn_title: 'Earn Points',
    orca_list_mypoints_earn_get_btn: 'Get Now',
    orca_list_mypoints_earn_got_btn: 'Got',
    Earned: 'Earned',
    points: 'points',
    orca_list_mypoints_history_title: 'Points History',
    orca_list_mypoints_history_all_btn: 'All',
    orca_list_mypoints_history_earnings_btn: 'Earned',
    orca_list_mypoints_history_expenses_btn: 'Spent',
    orca_list_mypoints_history_totalearnings: 'Total Earned: ',
    orca_list_mypoints_history_totalexpenses: 'Total Spent: ',
    orca_list_mypoints_history_time: 'Time',
    orca_list_mypoints_history_action: 'Action',
    orca_list_recent_aitopic_tips: 'One click to generate your custom AI model',
  },
};

var LANG_COOKIE_NAME = "BambuWebLang";
var LANG_COOKIE_EXPIRESECOND = 365 * 86400;

function TranslatePageMyPoint() {
  let strLang = GetQueryString("lang");
  if (strLang != null) {
    //setCookie(LANG_COOKIE_NAME,strLang,LANG_COOKIE_EXPIRESECOND,'/');
    localStorage.setItem(LANG_COOKIE_NAME, strLang);
  } else {
    //strLang=getCookie(LANG_COOKIE_NAME);
    strLang = localStorage.getItem(LANG_COOKIE_NAME);
  }

  // alert(strLang);

  if (!LangTextMyPoint.hasOwnProperty(strLang)) strLang = "en";

  let AllNode = $(".trans");
  let nTotal = AllNode.length;
  for (let n = 0; n < nTotal; n++) {
    let OneNode = AllNode[n];

    let tid = $(OneNode).attr("tid");
    if (LangTextMyPoint[strLang].hasOwnProperty(tid)) {
      $(OneNode).html(LangTextMyPoint[strLang][tid]);
    }
  }
}
